[app]
port = 8000

[db]
name = "newsletter"
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"

[email_client]
base_url = "localhost"
sender_email = "test@gmail.com"
timeout_ms = 10000
