[app]
port = 8000
hmac_secret = "super-long-and-secret-random-key-needed-to-verify-message-integrity"

[db]
name = "newsletter"
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"

[email_client]
base_url = "localhost"
sender_email = "test@gmail.com"
timeout_ms = 10000
api_key = "mailjet_api_key"
api_secret = "mailjet_api_secret"
